version: "2"

services:

  mongo:
    build: ./docker/mongo
    restart: always
    environment:
      - MONGODB_ADMIN_USER
      - MONGODB_ADMIN_PASS
      - MONGODB_APPLICATION_DATABASE
      - MONGODB_APPLICATION_USER
      - MONGODB_APPLICATION_PASS
    volumes_from:
      - mongodata
    ports:
      - "27019:27017"
    command: --auth

  mongoui:
    image: twnel/mongo-express
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD
      - ME_CONFIG_MONGODB_ENABLE_ADMIN
      - ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD
    ports:
      - "8081:8081"
    links:
      - mongo

  mongodata:
    image: tianon/true
    volumes:
      - /data/db

  redis:
    image: redis:4.0.5-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  redis-data: